#server
server:
  port: 8080
  servlet:
    context-path: /db
#HikariCP
spring:
  datasource:
    url: jdbc:mysql://120.77.211.78:3306/jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: learn
#thymaleaf
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
    cache: false
  aop:
    proxy-target-class: false  #jdk代理（优先使用jdk，在没有接口时会使用cglib）
  task:
    execution:
      pool:
        queue-capacity: 128
        core-size: 5
        max-size: 128
        keep-alive: 60000
        thread-name-prefix: db-service-task-
        
#mybatis
mybatis:
  mapper-locations:
  - classpath:/mapper/*/*.xml

#log
logging:
  level:
    com.cy: debug
    
async-thread-pool:
   corePoolSize: 20
   maxPoolSize: 1000
   keepAliveSeconds: 90
   queueCapacity: 1000


